### PR TITLE
Create PowershellScript-GC-2.ps1

### PR DESCRIPTION
**Pull request by nathansb2022**
A PowerShell script that downloads Go, adds it to the user's PATH, downloads the zip from the repository "looCiprian/GC2-sheet",
builds the executable, and runs gc2-sheet. Note: requires a web server to host the #MY_KEY_JSON file to Invoke-WebRequest down,
#MY_SHEET_ID, and #MY_DRIVE_ID to be incorporated into the PS1. Recommend using Invoke-RestMethod or Invoke-WebRequest to pull down
the contents of the file.

### CODE REVIEW

**Comment by elbae** [comment]
@nathansb2022 so the idea is to run the ps1 in the target windows server, where you download the source code, build it and run it.
but why?
why not just download the compiled version and run it?

**Comment by nathansb2022** [comment]
Well, that leads to the question, why is there not a compiled version in the GC2-sheet repository? There has to be a reason.

**Comment by looCiprian** [comment]
Hi @nathansb2022,

thank you for your pull request. To answer your question, currently, the repository does not provide compiled binaries for two main reasons:

1. I have a new commit ready to be pushed in the next few days, that deprecates the command line options in favour of a configuration file.
2. Prevent publicly available binary from being immediately uploaded to online malware analyzers (e.g., VirusTotal).

Your idea is great, but before merging it, I would like to review it and potentially create a make file to support cross-compiling.

**Comment by nathansb2022** [comment]
@looCiprian Thank you. This C2 is impressive due to its subtle behavior.

**Comment by looCiprian** [comment]
Hi @nathansb2022,

I've decided to close your pull request since the tool has been updated with the latest version. Furthermore, I would rather prefer to rely on a "make" file than on a PowerShell script to compile the C2.

Thank you for your idea!

**Pull request closed without merging**
